rabbitmq:
  url: "amqp://admin:admin@localhost"
  exchange:
    name: "master"
    type: "topic"
  queue:
    name: "my_queue"
    routing_key: "invoice.cmd.created"
kafka:
  brokers:
    - "localhost:9092"
  topic: "my_topic"
  group_id: "consumer-group-1"

logger:
  level: "info" # سطح لاگ مانند debug, info, warn, error