# configs/config.yaml

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "my_queue"
  routing_key: "my_routing_key"
  exchange_name: "events"
  exchange_type: "direct" # نوع تبادل مانند direct, topic, fanout و غیره

kafka:
  brokers:
    - "localhost:9092"
  topic: "my_topic"
  group_id: "consumer-group-1"

logger:
  level: "info" # سطح لاگ مانند debug, info, warn, error
 